### ISSUE TITLE
Reading version from package.json prevents presto-client from being used in a context that doesn't have a file system (ie: AWS Lambda)

### ISSUE THREAD

**Issue by treddeni** [tagomoris/presto-client-node#11]
In index.js you read the version from package.json.  Understandable, since you want to define the version in one place, but it prevents presto-client from being used in contexts that don't have a file system, like AWS Lambda.

https://github.com/tagomoris/presto-client-node/blob/master/index.js#L4

**Comment by tagomoris** [comment]
I have no idea about AWS lambda... Is that work well to do `require` on it?
If so, I'm ok to accept pull-requests to remove parsing JSON just for version number.

**Comment by treddeni** [comment]
I was building my lambda code into a single javascript file before deploying, but you can deploy a zip file that includes the node_modules directories.  When I deploy it that way, the presto-client works just fine running in AWS lambda.
Thanks, sorry about the confusion.
