### ISSUE TITLE
Add support for HTTPS connections

### ISSUE THREAD

**Issue by RohitTalwalkar** [tagomoris/presto-client-node#13]
It'd be great to have a client option that lets us specify HTTPS for Presto servers that are setup to encrypt traffic.

**Comment by tagomoris** [comment]
Sounds nice to have - welcome for patches :)

**Comment by kwent** [comment]
@RohitTalwalkar Look at https://github.com/tagomoris/presto-client-node/pull/15

**Comment by tagomoris** [comment]
#15 was merged.
