### ISSUE TITLE
Starting 0.161. /v1/execute resource got removed

### ISSUE THREAD

**Issue by kwent** [tagomoris/presto-client-node#14]
### Starting 0.161. /v1/execute resource got removed

Cf. https://prestodb.io/docs/current/release/release-0.161.html

And when trying to use https://github.com/tagomoris/presto-client-node#executearg-callback, the API is returning 404.

```js
{ message: 'execution error:<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>\n<title>Error 404 Not Found</title>\n</head>\n<body><h2>HTTP ERROR 404</h2>\n<p>Problem accessing /v1/execute. Reason:\n<pre>    Not Found</pre></p>\n</body>\n</html>\n', error: null, code: 404 }
```

I think the only way is to use `v1/statement` now.

**Comment by baixiaozhe** [comment]
up

**Comment by tagomoris** [comment]
Currently I have no motivation about it... Pull-requests are welcome.
