### ISSUE TITLE
Clarification needed on response

### ISSUE THREAD

**Issue by Santhoshas** [tagomoris/presto-client-node#16]
DATA callback method:
data [function(error, data, columns, stats) :optional] - called per fetch of query results (may be called 2 or more)
1. Is it possible to get results in a single callback?
2. Is it possible to get result data in SUCCESS callback method? - how to differentiate 201 and 204?

**Comment by tagomoris** [comment]
No for both, for now.
It's not difficult to add a callback function to get data at once at the end of query result. But Presto query results are sometimes very large, and containing such data on memory makes node.js process very unstable.
So I don't prefer such approach.

**Comment by Santhoshas** [comment]
Sorry to ask a very basic question. I am new to the node.
How to collect the response(from multiple query results) for a single request using DATA callback in the web application?
Do we need to write a logic to merge the query results from the multiple DATA callbacks and send the result in the SUCCESS callback?

**Comment by Santhoshas** [comment]
Thank you
