### ISSUE TITLE
Support for Authorization Header on all requests

### ISSUE THREAD

**Issue by martin-kieliszek** [tagomoris/presto-client-node#18]
Perhaps adding the following to Client.prototype.request function will enable use-cases that require auth on all requests:

in index.js, Client.prototype.request function
```
if (opts instanceof Object) {
    // other code as normal
    if (client.password && client.user){
          opts.headers[Headers.AUTHORIZATION] = 'Basic ' + new Buffer(client.user + ":" + client.password).toString("base64");
    }
   // other code as normal
}
```

This would require the headers.js file to also include the following:
```
Headers.AUTHORIZATION = 'Authorization';
```

The potential issue with this however, is for nextUri requests. nextUri requests enter the request function as a string, and not as an object. Hence, perhaps this could be a solution to ensure that nextUri requests still pass an Authorization header:

```
// Top of index.js
var parseUrl = require('parse-url');

// Within Client.prototype.request function
if (opts instanceof Object) {
   // omitting for this example
  } else {
// must be a nextUri request - hence it is a string that must have its protocol, host, port, pathname extracted and an AUTH header passed through - ONLY if a client.password is used
    if (client.password){
      var href = parseUrl(opts); 
      opts = {}
      opts.host = href.resource
      opts.port = href.port
      opts.protocol = client.protocol;
      opts.path = href.pathname;
      opts.headers = {};
      opts.headers[Headers.AUTHORIZATION] = 'Basic ' + new Buffer(client.user + ":" + client.password).toString("base64");
    }
  }
// Continue with request
```

Client password would be entered like so within the calling code:

```
var client = new presto.Client({user: 'user', password: 'pass', port: 8443, host: 'host.example', 
                                            catalog: 'hive', schema: 'default', 
                                              ssl: { cert: '/usr/local/share/ca-certificates/presto.crt'} });
```

Please comment or review

**Comment by tagomoris** [comment]
Option parameters (`user` and `password`) should be under `client.basic_auth` to explain explicitly that it's about basic authentication (not any other auth methods). Thus, we need to check `client.basic_auth` to check basic authentication should be enabled.
Others look good to me.

**Comment by martin-kieliszek** [comment]
Must I be an approved contributor prior to having the capability to push a new branch and do a pull request? 

Have currently forked and made a change to master, are you able to push it up in the absence of my ability to PR?

[https://github.com/martin-kieliszek/presto-client-node/commit/e8b06ab8b1abfb452d89db6e308d35e7abd91459](https://github.com/martin-kieliszek/presto-client-node/commit/e8b06ab8b1abfb452d89db6e308d35e7abd91459)

Thanks again for your management and contributions to this library @tagomoris
