### ISSUE TITLE
SSL redirect failing

### ISSUE THREAD

**Issue by souryabharath** [tagomoris/presto-client-node#33]
When I tried to connect to presto server using the presto-client library with SSL (cert and key info) and run execute query the REST call to /v1/statement works and when the client tried to hit the "nextUri" endpoint, the server returns 401 due to missing certificate information while making the call.

This PR fixes that issue. Please review and let me know.

https://github.com/tagomoris/presto-client-node/compare/master...souryabharath:patch-1

**Comment by tagomoris** [comment]
Just for note: #34

**Comment by tagomoris** [comment]
@souryabharath I've created a different change to fix this problem, as the branch `apply-ssl-options-in-fetching-nexturi`.
Can you fetch that branch and check it if it actually fixes your problem?

**Comment by souryabharath** [comment]
@tagomoris The new changes fixed the redirect issue.

**Comment by tagomoris** [comment]
#35 fixes this issue.
