### ISSUE TITLE
Add support for Trino

### ISSUE THREAD

**Issue by guillaume-fr** [tagomoris/presto-client-node#44]
PrestoSQL is now Trino and changed few bits on the protocol.
https://trino.io/blog/2020/12/27/announcing-trino.html

I'm getting an error on User missing as the server expects X-Trino headers instead of X-Presto.
Hack to get this lib working with Trino, run this before any request:
```
const Headers = require('presto-client/lib/presto-client/headers').Headers;
for (let key of Object.keys(Headers)) {
    Headers[key] = Headers[key].replace("Presto", "Trino");
}
```

**Comment by tagomoris** [comment]
@guillaume-fr Can you create a pull-req for that? Or is someone else interested in it?
It should be:
* having 2 sets of `Headers`
* switch headers by constructor option or something else

**Comment by deugene** [comment]
https://github.com/tagomoris/presto-client-node/pull/46

**Comment by deugene** [comment]
> @guillaume-fr Can you create a pull-req for that? Or is someone else interested in it?
> It should be:
> 
> * having 2 sets of `Headers`
> * switch headers by constructor option or something else

https://github.com/tagomoris/presto-client-node/pull/46

**Comment by deugene** [comment]
#46

**Comment by tagomoris** [comment]
#46 fixed this.
