### ISSUE TITLE
Discussion: support kerberos authentication

### ISSUE THREAD

**Issue by johnson-liang** [tagomoris/presto-client-node#47]
I am trying to connect to a Trino server guarded with Kerberos authentication.

Currently the authorization header is designated here, in HTTP basic auth: https://github.com/tagomoris/presto-client-node/blob/master/lib/presto-client/index.js#L98

I think there are 2 ways to implement Kerberos support:
1. Introduce a new option `custom_auth` in `Client` constructor `opts` for a custom authorization header string. When present, it will set authorization header as specified somewhere near [here in the code](https://github.com/tagomoris/presto-client-node/blob/master/lib/presto-client/index.js#L98). Developers must find their own way to generate the authorization header (for Kerberos it means using other libraries like [kerberos](https://github.com/mongodb-js/kerberos) or [krb5](https://github.com/adaltas/node-krb5#readme).)
2. Introduce an optional dependency [`kerberos`](https://github.com/mongodb-js/kerberos) and support kerberos authentication similar to [PyHive's](https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L95-L97).

Personally I prefer 1 because it introduces less code change on the library. If this is preferred, I can submit a pull request on this :)

**Comment by tagomoris** [comment]
@johnson-liang That idea sounds nice to me too :D
