### ISSUE TITLE
timeZoneId is null

### ISSUE THREAD

**Issue by pawelrychlik** [tagomoris/presto-client-node#6]
I ran into a NullPointer problem upon running this very simple script:

```
var presto = require('presto-client');
var client = new presto.Client({ catalog: 'cassandra', schema: 'test' });

client.execute({ query: 'show tables' }, function(error, data, columns) {
  if (error) return console.log(error);
  console.log(data);
});
```

The error I get:
```
{ message: 'execution error:java.lang.NullPointerException: timeZoneId is null\n\tat java.util.Objects.requireNonNull(Objects.java:228)\n\tat com.facebook.presto.client.ClientSession.<init>(ClientSession.java:144) .........',
  error: null,
  code: 500 }
```

So I jumped into prestodb code and it turns out that the timeZoneId is required https://github.com/prestodb/presto/commit/f8ceb1757dba59e1dd1fbdf17b918a1ba0153e99#diff-a804c427cefb2a1682c3bea281daf18aR68

I'm running prestodb 0.157.

**Comment by johngroves** [comment]
Same problem, w/ latest AWS EMR version. Thanks for the fix!

**Comment by JonahTurnquist** [comment]
Same problem

**Comment by lourenzo** [comment]
Same problem

**Comment by tagomoris** [comment]
Version `0.1.3` should fix this problem. Could you try to update this library?

**Comment by saharza** [comment]
I running version - 0.1.3 and still the same problem...
