### ISSUE TITLE
Queries from Node client 100x slower than from Trino CLI

### ISSUE THREAD

**Issue by patxu** [tagomoris/presto-client-node#89]
I'm using this Node client to query Trino running in a local container. Simple queries such as `SELECT NULL;` take 1-2 seconds as seen in the Trino query console, while the same query issued from the CLI complete in milliseconds. Is this expected, can I improve my configuration, or are there any improvements to the driver that can be made?

![image](https://github.com/tagomoris/presto-client-node/assets/6548282/266616f2-4326-4833-81ae-699c1e3a06c4)
![image](https://github.com/tagomoris/presto-client-node/assets/6548282/c84ba7de-8636-4fd0-a221-cacb158d6ff2)

**Comment by patxu** [comment]
@noxify cheers, thanks for the suggestion. The results are pretty noticable – I'm seeing an almost linear decrease in the time it takes to run queries as I reduce the poll interval.

It's somewhat concerning that you experienced some http errors when you were testing this. Everything looks stable in my setup currently – hopefully nothing unexpected pops up later!

**Comment by noxify** [comment]
@patxu - thanks for the update.

We have currently some performance problems with the trino server.

In our case, we use the `presto-client-node` for our graphql wrapper.
If the api consumer runs multiple requests ( e.g. via paging ) against a table with 2 million+ records, then the cpu load is 98%  and the response time moves from 2s to +20s.

We get this performance issue also when we use the odbc driver from starburst, so it's a general problem or we use the wrong software ( trino ) for our use case 🙈
