### ISSUE TITLE
Prepare statement too large for header

### ISSUE THREAD

**Issue by patxu** [tagomoris/presto-client-node#90]
I'm passing in a large `prepare` query but unfortunately getting a response like `Error: execution error: Bad Message 431 reason: Request Header Fields Too Large`. These queries are defined by 3rd parties so I don't have direct control over it. 

My goal is to `DESCRIBE OUTPUT preparedQuery`, but I can't do this if preparing the query fails. Any workaround or suggestions?

**Comment by tagomoris** [comment]
I have completely no idea which HTTP headers you're sending or what query engine you're using (Presto or Trino, version, etc). The most important thing is that you should have control of our query by yourself.
Anyway, I don't know anything about it.
How about dump and check the all headers and the request body then check Presto/Trino's limitations of those things?

**Comment by aromalsanthosh** [comment]
@tagomoris I'm also facing a similar issue for a large prepare statement. I'm using presto engine. Passing a large prepare statemen in header. Is this a limitation with presto?
